### PR TITLE
[pwndoc/pwndoc[#355] [#333]] Upgrade codeblock function + TipTap V2 + Highlighting + [pwndoc/pwndoc[#330]] special character in code block broke xml in doc export 

### PR DESCRIPTION
**Pull request by nitek29**
[pwndoc/pwndoc#355](https://github.com/pwndoc/pwndoc/issues/355)
[pwndoc/pwndoc#355](https://github.com/pwndoc/pwndoc/issues/333)
[pwndoc/pwndoc#355](https://github.com/pwndoc/pwndoc/issues/330)
#2 
+ TiptapV2
+ Highlighting

### CODE REVIEW

**Comment by RobertDoc** [comment]
Looks like there is a regression and can no longer mark things as `code` or `code blocks`, is it possible to readd those?

**Comment by nitek29** [comment]
Hello, 
The "table" function I have developed is misnamed it is more a replacement for `code` and `code block`, indeed my code allows the use of highlighting, bold, italic.
So, because of my new `code block` function, I disable the use of multiple columns and rows.
Sorry for the confusion

**Comment by RobertDoc** [comment]
No worries, I have made a PR #12 that adds the buttons for code and codeblock back to the toolbar. It also generates dynamic tables which I think would be the expected functionality, I have used this PR as a base

**Comment by drunkentortoise** [comment]
Hello,

Kudos for all the new features and the enhancements. 

Just a quick question, due to the upgrade of the codeblock function and TipTapv2, some filter features such as bookmarkCreate, bookmarklink and linkTo are no longer present in the report-generator.js. For now, I was able to recover the js file from the initial commit as a workaround. 

Is there a possibility for seeing these filters back in the TipTapv2 main branch ? Or can I just simply slap them into the main branch's .js file with code block syntaxes ? 

Thanks in advance :)

**Comment by Zeecka** [comment]
@drunkentortoise I just opened an issue https://github.com/pwndoc-ng/pwndoc-ng/issues/39 according to your comment. I think we need to fix this ASAP, I'll check on thix but you can PR if you want to :).

**Pull request merged**
